# coding: utf-8

"""
    bag

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.bag_onderzoeken_link import BagOnderzoekenLink
from openapi_client import configuration


class TestBagOnderzoekenLink(unittest.TestCase):
    """BagOnderzoekenLink unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
