# coding: utf-8

"""
    bag

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class BagNummeraanduidingenLinks(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The contents of the `nummeraanduidingen._links` field. It contains all relationships with objects.
    """


    class MetaOapg:
        required = {
            "schema",
            "heeftDossier",
            "ligtAanOpenbareruimte",
            "adresseertVerblijfsobject",
            "self",
            "adresseertStandplaats",
            "heeftOnderzoeken",
            "ligtInWoonplaats",
            "adresseertLigplaats",
        }
        
        class properties:
            schema = schemas.StrSchema
        
            @staticmethod
            def _self() -> typing.Type['BagNummeraanduidingenLink']:
                return BagNummeraanduidingenLink
        
            @staticmethod
            def ligtInWoonplaats() -> typing.Type['BagWoonplaatsenLink']:
                return BagWoonplaatsenLink
        
            @staticmethod
            def ligtAanOpenbareruimte() -> typing.Type['BagOpenbareruimtesLink']:
                return BagOpenbareruimtesLink
        
            @staticmethod
            def adresseertVerblijfsobject() -> typing.Type['BagVerblijfsobjectenLink']:
                return BagVerblijfsobjectenLink
        
            @staticmethod
            def adresseertLigplaats() -> typing.Type['BagLigplaatsenLink']:
                return BagLigplaatsenLink
        
            @staticmethod
            def adresseertStandplaats() -> typing.Type['BagStandplaatsenLink']:
                return BagStandplaatsenLink
        
            @staticmethod
            def heeftDossier() -> typing.Type['BagdossiersLink']:
                return BagdossiersLink
            
            
            class heeftOnderzoeken(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['BagnummeraanduidingenHeeftOnderzoekenM2M']:
                        return BagnummeraanduidingenHeeftOnderzoekenM2M
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['BagnummeraanduidingenHeeftOnderzoekenM2M'], typing.List['BagnummeraanduidingenHeeftOnderzoekenM2M']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'heeftOnderzoeken':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'BagnummeraanduidingenHeeftOnderzoekenM2M':
                    return super().__getitem__(i)
            __annotations__ = {
                "schema": schema,
                "self": _self,
                "ligtInWoonplaats": ligtInWoonplaats,
                "ligtAanOpenbareruimte": ligtAanOpenbareruimte,
                "adresseertVerblijfsobject": adresseertVerblijfsobject,
                "adresseertLigplaats": adresseertLigplaats,
                "adresseertStandplaats": adresseertStandplaats,
                "heeftDossier": heeftDossier,
                "heeftOnderzoeken": heeftOnderzoeken,
            }
    
    schema: MetaOapg.properties.schema
    heeftDossier: 'BagdossiersLink'
    ligtAanOpenbareruimte: 'BagOpenbareruimtesLink'
    adresseertVerblijfsobject: 'BagVerblijfsobjectenLink'
    adresseertStandplaats: 'BagStandplaatsenLink'
    heeftOnderzoeken: MetaOapg.properties.heeftOnderzoeken
    ligtInWoonplaats: 'BagWoonplaatsenLink'
    adresseertLigplaats: 'BagLigplaatsenLink'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["schema"]) -> MetaOapg.properties.schema: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["self"]) -> 'BagNummeraanduidingenLink': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ligtInWoonplaats"]) -> 'BagWoonplaatsenLink': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ligtAanOpenbareruimte"]) -> 'BagOpenbareruimtesLink': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["adresseertVerblijfsobject"]) -> 'BagVerblijfsobjectenLink': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["adresseertLigplaats"]) -> 'BagLigplaatsenLink': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["adresseertStandplaats"]) -> 'BagStandplaatsenLink': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["heeftDossier"]) -> 'BagdossiersLink': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["heeftOnderzoeken"]) -> MetaOapg.properties.heeftOnderzoeken: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["schema", "self", "ligtInWoonplaats", "ligtAanOpenbareruimte", "adresseertVerblijfsobject", "adresseertLigplaats", "adresseertStandplaats", "heeftDossier", "heeftOnderzoeken", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["schema"]) -> MetaOapg.properties.schema: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["self"]) -> 'BagNummeraanduidingenLink': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ligtInWoonplaats"]) -> 'BagWoonplaatsenLink': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ligtAanOpenbareruimte"]) -> 'BagOpenbareruimtesLink': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["adresseertVerblijfsobject"]) -> 'BagVerblijfsobjectenLink': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["adresseertLigplaats"]) -> 'BagLigplaatsenLink': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["adresseertStandplaats"]) -> 'BagStandplaatsenLink': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["heeftDossier"]) -> 'BagdossiersLink': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["heeftOnderzoeken"]) -> MetaOapg.properties.heeftOnderzoeken: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["schema", "self", "ligtInWoonplaats", "ligtAanOpenbareruimte", "adresseertVerblijfsobject", "adresseertLigplaats", "adresseertStandplaats", "heeftDossier", "heeftOnderzoeken", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        schema: typing.Union[MetaOapg.properties.schema, str, ],
        heeftDossier: 'BagdossiersLink',
        ligtAanOpenbareruimte: 'BagOpenbareruimtesLink',
        adresseertVerblijfsobject: 'BagVerblijfsobjectenLink',
        adresseertStandplaats: 'BagStandplaatsenLink',
        heeftOnderzoeken: typing.Union[MetaOapg.properties.heeftOnderzoeken, list, tuple, ],
        ligtInWoonplaats: 'BagWoonplaatsenLink',
        adresseertLigplaats: 'BagLigplaatsenLink',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BagNummeraanduidingenLinks':
        return super().__new__(
            cls,
            *_args,
            schema=schema,
            heeftDossier=heeftDossier,
            ligtAanOpenbareruimte=ligtAanOpenbareruimte,
            adresseertVerblijfsobject=adresseertVerblijfsobject,
            adresseertStandplaats=adresseertStandplaats,
            heeftOnderzoeken=heeftOnderzoeken,
            ligtInWoonplaats=ligtInWoonplaats,
            adresseertLigplaats=adresseertLigplaats,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.bag_ligplaatsen_link import BagLigplaatsenLink
from openapi_client.model.bag_nummeraanduidingen_link import BagNummeraanduidingenLink
from openapi_client.model.bag_openbareruimtes_link import BagOpenbareruimtesLink
from openapi_client.model.bag_standplaatsen_link import BagStandplaatsenLink
from openapi_client.model.bag_verblijfsobjecten_link import BagVerblijfsobjectenLink
from openapi_client.model.bag_woonplaatsen_link import BagWoonplaatsenLink
from openapi_client.model.bagdossiers_link import BagdossiersLink
from openapi_client.model.bagnummeraanduidingen_heeft_onderzoeken_m2_m import BagnummeraanduidingenHeeftOnderzoekenM2M
