# coding: utf-8

"""
    bag

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class BagDossiersLinks(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The contents of the `dossiers._links` field. It contains all relationships with objects.
    """


    class MetaOapg:
        required = {
            "schema",
            "self",
            "heeftBrondocumenten",
        }
        
        class properties:
            schema = schemas.StrSchema
        
            @staticmethod
            def _self() -> typing.Type['BagdossiersLink']:
                return BagdossiersLink
            
            
            class heeftBrondocumenten(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['BagdossiersHeeftBrondocumentenM2M']:
                        return BagdossiersHeeftBrondocumentenM2M
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['BagdossiersHeeftBrondocumentenM2M'], typing.List['BagdossiersHeeftBrondocumentenM2M']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'heeftBrondocumenten':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'BagdossiersHeeftBrondocumentenM2M':
                    return super().__getitem__(i)
            __annotations__ = {
                "schema": schema,
                "self": _self,
                "heeftBrondocumenten": heeftBrondocumenten,
            }
    
    schema: MetaOapg.properties.schema
    heeftBrondocumenten: MetaOapg.properties.heeftBrondocumenten
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["schema"]) -> MetaOapg.properties.schema: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["self"]) -> 'BagdossiersLink': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["heeftBrondocumenten"]) -> MetaOapg.properties.heeftBrondocumenten: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["schema", "self", "heeftBrondocumenten", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["schema"]) -> MetaOapg.properties.schema: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["self"]) -> 'BagdossiersLink': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["heeftBrondocumenten"]) -> MetaOapg.properties.heeftBrondocumenten: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["schema", "self", "heeftBrondocumenten", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        schema: typing.Union[MetaOapg.properties.schema, str, ],
        heeftBrondocumenten: typing.Union[MetaOapg.properties.heeftBrondocumenten, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BagDossiersLinks':
        return super().__new__(
            cls,
            *_args,
            schema=schema,
            heeftBrondocumenten=heeftBrondocumenten,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.bagdossiers_heeft_brondocumenten_m2_m import BagdossiersHeeftBrondocumentenM2M
from openapi_client.model.bagdossiers_link import BagdossiersLink
