# coding: utf-8

"""
    bag

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class Bagonderzoeken(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    onderzoeken
    """


    class MetaOapg:
        required = {
            "identificatie",
            "_links",
            "volgnummer",
        }
        
        class properties:
            
            
            class _links(
                schemas.ComposedSchema,
            ):
            
            
                class MetaOapg:
                    
                    @classmethod
                    @functools.lru_cache()
                    def all_of(cls):
                        # we need this here to make our import statements work
                        # we must store _composed_schemas in here so the code is only run
                        # when we invoke this method. If we kept this at the class
                        # level we would get an error because the class level
                        # code would be run when this module is imported, and these composed
                        # classes don't exist yet because their module has not finished
                        # loading
                        return [
                            BagOnderzoekenLinks,
                        ]
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> '_links':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class identificatie(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 2147483647
            
            
            class volgnummer(
                schemas.Int64Schema
            ):
            
            
                class MetaOapg:
                    format = 'int64'
                    inclusive_maximum = 9223372036854775807
                    inclusive_minimum = -9223372036854775808
            
            
            class registratiedatum(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'registratiedatum':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class objectIdentificatie(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 2147483647
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'objectIdentificatie':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class objecttype(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 2147483647
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'objecttype':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class kenmerk(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 2147483647
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'kenmerk':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class inOnderzoek(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 2147483647
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'inOnderzoek':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class beginGeldigheid(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'beginGeldigheid':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class eindGeldigheid(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'eindGeldigheid':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class documentdatum(
                schemas.DateBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, date, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'documentdatum':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class documentnummer(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 2147483647
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'documentnummer':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class tijdstipRegistratie(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tijdstipRegistratie':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class eindRegistratie(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'eindRegistratie':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "_links": _links,
                "identificatie": identificatie,
                "volgnummer": volgnummer,
                "registratiedatum": registratiedatum,
                "objectIdentificatie": objectIdentificatie,
                "objecttype": objecttype,
                "kenmerk": kenmerk,
                "inOnderzoek": inOnderzoek,
                "beginGeldigheid": beginGeldigheid,
                "eindGeldigheid": eindGeldigheid,
                "documentdatum": documentdatum,
                "documentnummer": documentnummer,
                "tijdstipRegistratie": tijdstipRegistratie,
                "eindRegistratie": eindRegistratie,
            }
    
    identificatie: MetaOapg.properties.identificatie
    _links: MetaOapg.properties._links
    volgnummer: MetaOapg.properties.volgnummer
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["_links"]) -> MetaOapg.properties._links: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["identificatie"]) -> MetaOapg.properties.identificatie: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["volgnummer"]) -> MetaOapg.properties.volgnummer: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["registratiedatum"]) -> MetaOapg.properties.registratiedatum: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["objectIdentificatie"]) -> MetaOapg.properties.objectIdentificatie: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["objecttype"]) -> MetaOapg.properties.objecttype: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kenmerk"]) -> MetaOapg.properties.kenmerk: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["inOnderzoek"]) -> MetaOapg.properties.inOnderzoek: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["beginGeldigheid"]) -> MetaOapg.properties.beginGeldigheid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["eindGeldigheid"]) -> MetaOapg.properties.eindGeldigheid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["documentdatum"]) -> MetaOapg.properties.documentdatum: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["documentnummer"]) -> MetaOapg.properties.documentnummer: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tijdstipRegistratie"]) -> MetaOapg.properties.tijdstipRegistratie: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["eindRegistratie"]) -> MetaOapg.properties.eindRegistratie: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["_links", "identificatie", "volgnummer", "registratiedatum", "objectIdentificatie", "objecttype", "kenmerk", "inOnderzoek", "beginGeldigheid", "eindGeldigheid", "documentdatum", "documentnummer", "tijdstipRegistratie", "eindRegistratie", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["_links"]) -> MetaOapg.properties._links: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["identificatie"]) -> MetaOapg.properties.identificatie: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["volgnummer"]) -> MetaOapg.properties.volgnummer: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["registratiedatum"]) -> typing.Union[MetaOapg.properties.registratiedatum, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["objectIdentificatie"]) -> typing.Union[MetaOapg.properties.objectIdentificatie, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["objecttype"]) -> typing.Union[MetaOapg.properties.objecttype, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kenmerk"]) -> typing.Union[MetaOapg.properties.kenmerk, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["inOnderzoek"]) -> typing.Union[MetaOapg.properties.inOnderzoek, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["beginGeldigheid"]) -> typing.Union[MetaOapg.properties.beginGeldigheid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["eindGeldigheid"]) -> typing.Union[MetaOapg.properties.eindGeldigheid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["documentdatum"]) -> typing.Union[MetaOapg.properties.documentdatum, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["documentnummer"]) -> typing.Union[MetaOapg.properties.documentnummer, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tijdstipRegistratie"]) -> typing.Union[MetaOapg.properties.tijdstipRegistratie, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["eindRegistratie"]) -> typing.Union[MetaOapg.properties.eindRegistratie, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["_links", "identificatie", "volgnummer", "registratiedatum", "objectIdentificatie", "objecttype", "kenmerk", "inOnderzoek", "beginGeldigheid", "eindGeldigheid", "documentdatum", "documentnummer", "tijdstipRegistratie", "eindRegistratie", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        identificatie: typing.Union[MetaOapg.properties.identificatie, str, ],
        _links: typing.Union[MetaOapg.properties._links, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        volgnummer: typing.Union[MetaOapg.properties.volgnummer, decimal.Decimal, int, ],
        registratiedatum: typing.Union[MetaOapg.properties.registratiedatum, None, str, datetime, schemas.Unset] = schemas.unset,
        objectIdentificatie: typing.Union[MetaOapg.properties.objectIdentificatie, None, str, schemas.Unset] = schemas.unset,
        objecttype: typing.Union[MetaOapg.properties.objecttype, None, str, schemas.Unset] = schemas.unset,
        kenmerk: typing.Union[MetaOapg.properties.kenmerk, None, str, schemas.Unset] = schemas.unset,
        inOnderzoek: typing.Union[MetaOapg.properties.inOnderzoek, None, str, schemas.Unset] = schemas.unset,
        beginGeldigheid: typing.Union[MetaOapg.properties.beginGeldigheid, None, str, datetime, schemas.Unset] = schemas.unset,
        eindGeldigheid: typing.Union[MetaOapg.properties.eindGeldigheid, None, str, datetime, schemas.Unset] = schemas.unset,
        documentdatum: typing.Union[MetaOapg.properties.documentdatum, None, str, date, schemas.Unset] = schemas.unset,
        documentnummer: typing.Union[MetaOapg.properties.documentnummer, None, str, schemas.Unset] = schemas.unset,
        tijdstipRegistratie: typing.Union[MetaOapg.properties.tijdstipRegistratie, None, str, datetime, schemas.Unset] = schemas.unset,
        eindRegistratie: typing.Union[MetaOapg.properties.eindRegistratie, None, str, datetime, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Bagonderzoeken':
        return super().__new__(
            cls,
            *_args,
            identificatie=identificatie,
            _links=_links,
            volgnummer=volgnummer,
            registratiedatum=registratiedatum,
            objectIdentificatie=objectIdentificatie,
            objecttype=objecttype,
            kenmerk=kenmerk,
            inOnderzoek=inOnderzoek,
            beginGeldigheid=beginGeldigheid,
            eindGeldigheid=eindGeldigheid,
            documentdatum=documentdatum,
            documentnummer=documentnummer,
            tijdstipRegistratie=tijdstipRegistratie,
            eindRegistratie=eindRegistratie,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.bag_onderzoeken_links import BagOnderzoekenLinks
