# coding: utf-8

"""
    bag

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_bag_ligplaatsen_.get import BagLigplaatsenList
from openapi_client.paths.v1_bag_ligplaatsen_id_.get import BagLigplaatsenRetrieve


class LigplaatsenApi(
    BagLigplaatsenList,
    BagLigplaatsenRetrieve,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
