# coding: utf-8

"""
    bag

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_bag_openbareruimtes_.get import BagOpenbareruimtesList
from openapi_client.paths.v1_bag_openbareruimtes_id_.get import BagOpenbareruimtesRetrieve


class OpenbareruimtesApi(
    BagOpenbareruimtesList,
    BagOpenbareruimtesRetrieve,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
