# coding: utf-8

"""
    bag

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_bag_panden_.get import BagPandenList
from openapi_client.paths.v1_bag_panden_id_.get import BagPandenRetrieve


class PandenApi(
    BagPandenList,
    BagPandenRetrieve,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
