# coding: utf-8

"""
    bag

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_bag_verblijfsobjecten_.get import BagVerblijfsobjectenList
from openapi_client.paths.v1_bag_verblijfsobjecten_id_.get import BagVerblijfsobjectenRetrieve


class VerblijfsobjectenApi(
    BagVerblijfsobjectenList,
    BagVerblijfsobjectenRetrieve,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
